{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Order Latencyu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "order_latency", "legendFormat": "Pizza Latency" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_sold{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizza_creationErrors{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_latency{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_memoryUsage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory Use"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_successful{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "success"
    },
    { "expr": "rate(auth_failed[1m])", "legendFormat": "failure" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_cpuUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "user_active{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service-dev\"} |= ``"
    }
   ]
  }
 ]
}